### ISSUE TITLE
Resolve UB found by miri

### ISSUE THREAD

**Issue by xfix** [servo/tendril#41]
Miri reports plenty of UB in Tendril crate. It can be tested checked using `cargo miri test` (on nightly).

**Comment by Manishearth** [comment]
Ah, this is all just MaybeUninit.

**Comment by Manishearth** [comment]
Oh, this is trickier to fix, we use `write!()` on an uninit value at least once

**Comment by SimonSapin** [comment]
Uses of `mem::uninitialized` are now gone, but `cargo miri test` still errors.

There is plenty of unnecessary or dubious `unsafe` code in this crate, enough to make it tempting (for me) to write a new library rather than go through all of it. (The whole generic "format" thing is also unnecessary, we’d be fine with just `BytesTendril` and `StrTendril` that wraps it.)
