### ISSUE TITLE
Implement a rope for Tendrils

### ISSUE THREAD

**Issue by kmcallister** [servo/tendril#5]
`VecDeque<Tendril<F>>` should perform well up to moderate chunk counts, since `Tendril` is a small structure. But we might consider switching to a [2-3 finger tree](http://staff.city.ac.uk/~ross/papers/FingerTree.html) at some size.  Do we need persistent append (i.e. `Rope + Rope -> Rope`) or only in-place?

**Comment by andrebeat** [comment]
I've started implementing a finger tree in rust (https://github.com/andrebeat/fingers). The data types are slightly different from the original Haskell definition since Rust lacks polymorphic recursion. The current implementation is persistent and uses Rc for subtree sharing. Also, in order for the complexity bounds to hold it is necessary for the middle subtree to be lazily evaluated which it currently isn't.
Do you think this is something that could be useful for the purposes of tendril?

**Comment by SimonSapin** [comment]
This sounds interesting, but I don’t think anyone is pursuing this kind of thing actively at the moment. Or maybe @asajeffrey?

**Comment by asajeffrey** [comment]
I'm currently doing experiments with string representations. This could be pretty cool, especially if it's parametric over the representation of flat strings.

**Comment by asajeffrey** [comment]
I mean implement FingerTree<T> and then show (for example) FingerTree<T>
impl ToIter<char> where T impl ToIter<char>, and ditto the other traits for
strings.

Ropes are used for more than just huge strings, they're used for O(1) edit
operations, for example expanding entities.

A.

**Comment by andrebeat** [comment]
Ah, I think I understand what you mean and it makes perfect sense! Taking your example, if I can interpret a `Tendril` as being a sequence of `u8` or `char`, I should also be able to achieve the same representation when using a `FingerTree<Tendril>`, hiding away the fact that we're using a non-contiguous representation for the data.
